### ISSUE TITLE
Runtime evaluation

### ISSUE THREAD

**Issue by straight-shoota** [veelenga/any_setting#1]
I think it would be nice if configuration values are evaluated at runtime so you don't need to recompile a binary just to change a setting. Obviously, this is impossible if the config file is loaded at compile time and rendered with ECR.
Otherwise, this is a great idea, I had a similar thoughts and there is also an example for crinja for evaluating configuration values: https://github.com/straight-shoota/crinja/blob/master/examples/config/config.cr
It's also possible to include (evaluated) other values inside a template expression ;)
Like this:
```yaml
title: My Super Site
date: 2017-07-18
slug: "{{date}}-{{ title | underscore }}"
```
